#!/usr/bin/env python3
"""Convert the fine-tuning experiment summary CSV into a LaTeX table."""

import argparse
import csv
from pathlib import Path


# Default summary produced by finetune_qwen_lora_vs_full.py.
DEFAULT_INPUT_PATH = Path("results/qwen_lora_vs_full/summary.csv")

# Default location for the generated LaTeX table.
DEFAULT_OUTPUT_PATH = Path("results/qwen_lora_vs_full/summary_table.tex")

# CSV columns required to construct the table.
REQUIRED_COLUMNS = {
    "configuration",
    "trainable_parameters",
    "trainable_percent",
    "peak_reserved_gib",
    "peak_reserved_percent",
    "training_time_seconds",
    "final_training_loss",
    "final_validation_loss",
}


# Parse input/output paths supplied on the command line.
def parse_args() -> argparse.Namespace:
    # Command-line interface for the converter.
    parser = argparse.ArgumentParser(
        description="Convert a Qwen fine-tuning summary CSV to a LaTeX table."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT_PATH,
        help=f"input summary CSV (default: {DEFAULT_INPUT_PATH})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help=f"output LaTeX file (default: {DEFAULT_OUTPUT_PATH})",
    )
    return parser.parse_args()


# Escape characters that have special meaning in ordinary LaTeX text.
def escape_latex(value: str) -> str:
    # Ordered character replacements for a table cell.
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    # Escaped output accumulated one source character at a time.
    return "".join(replacements.get(character, character) for character in value)


# Read and validate rows from the experiment summary.
def read_summary(path: Path) -> list[dict[str, str]]:
    if not path.is_file():
        raise SystemExit(f"Input summary does not exist: {path}")

    with path.open(newline="", encoding="utf-8") as csv_file:
        # Dictionary-based reader retaining the CSV column names.
        reader = csv.DictReader(csv_file)
        # Columns found in the input header.
        present_columns = set(reader.fieldnames or [])
        # Required columns absent from the input header.
        missing_columns = sorted(REQUIRED_COLUMNS - present_columns)
        if missing_columns:
            raise SystemExit(
                "Input CSV is missing required columns: " + ", ".join(missing_columns)
            )
        # All experiment configurations in their original order.
        rows = list(reader)

    if not rows:
        raise SystemExit(f"Input summary contains no data rows: {path}")
    return rows


# Render a numeric CSV value with a fixed number of decimal places.
def format_decimal(value: str, decimal_places: int) -> str:
    try:
        return f"{float(value):.{decimal_places}f}"
    except ValueError as error:
        raise SystemExit(f"Expected a numeric value, received {value!r}.") from error


# Render an integer parameter count with comma grouping.
def format_integer(value: str) -> str:
    try:
        return f"{int(value):,}"
    except ValueError as error:
        raise SystemExit(f"Expected an integer value, received {value!r}.") from error


# Build a complete booktabs-compatible LaTeX table.
def build_latex_table(rows: list[dict[str, str]]) -> str:
    # Generated table source, one LaTeX line per list item.
    lines = [
        "% Generated by finetuning_summary_to_latex.py; do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{Qwen2.5-0.5B fine-tuning results on the fixed UltraChat subset. Peak GPU memory is PyTorch peak reserved memory.}",
        r"\label{tab:qwen-lora-vs-full}",
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        r"Configuration & Trainable params. & Trainable (\%) & Peak memory (GiB) & Peak GPU (\%) & Time (s) & Final train / val. loss \\",
        r"\midrule",
    ]

    for row in rows:
        # Display name for the training configuration.
        configuration = escape_latex(row["configuration"])
        # Trainable parameter count with thousands separators.
        trainable_parameters = format_integer(row["trainable_parameters"])
        # Percentage of model parameters updated during training.
        trainable_percent = format_decimal(row["trainable_percent"], 3)
        # Peak PyTorch reserved GPU memory in GiB.
        peak_memory = format_decimal(row["peak_reserved_gib"], 2)
        # Peak PyTorch reserved memory as a percentage of GPU capacity.
        peak_percent = format_decimal(row["peak_reserved_percent"], 1)
        # Measured training-loop wall-clock time in seconds.
        training_time = format_decimal(row["training_time_seconds"], 1)
        # Last recorded training loss.
        training_loss = format_decimal(row["final_training_loss"], 4)
        # Final held-out validation loss.
        validation_loss = format_decimal(row["final_validation_loss"], 4)
        lines.append(
            f"{configuration} & {trainable_parameters} & {trainable_percent} & "
            f"{peak_memory} & {peak_percent} & {training_time} & "
            f"{training_loss} / {validation_loss} " + r"\\"
        )

    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
            "",
        ]
    )
    return "\n".join(lines)


# Convert the requested CSV file and write the resulting LaTeX source.
def main() -> None:
    # User-selected input and output locations.
    args = parse_args()
    # Validated experiment summary rows.
    rows = read_summary(args.input)
    # Complete rendered LaTeX table.
    latex_source = build_latex_table(rows)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(latex_source, encoding="utf-8")
    print(f"Wrote LaTeX table: {args.output}")


if __name__ == "__main__":
    main()
