#!/usr/bin/env python3
"""Convert qualitative generation comparisons from JSON to a LaTeX fragment."""

import argparse
import json
from pathlib import Path
from typing import Any


# Default qualitative report produced by finetune_qwen_lora_vs_full.py.
DEFAULT_INPUT_PATH = Path(
    "results/qwen_lora_vs_full_5epochs/qualitative_generations.json"
)

# Default destination for the generated LaTeX fragment.
DEFAULT_OUTPUT_PATH = Path(
    "results/qwen_lora_vs_full_5epochs/qualitative_generations.tex"
)

# Preferred display order for the model responses.
MODEL_ORDER = [
    "Base model",
    "LoRA r=1",
    "LoRA r=4",
    "LoRA r=16",
    "Full fine-tuning",
]


# Parse converter paths and reference-answer preferences.
def parse_args() -> argparse.Namespace:
    # Command-line interface for the JSON-to-LaTeX converter.
    parser = argparse.ArgumentParser(
        description="Convert qualitative model generations to a LaTeX fragment."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT_PATH,
        help=f"input generations JSON (default: {DEFAULT_INPUT_PATH})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help=f"output LaTeX file (default: {DEFAULT_OUTPUT_PATH})",
    )
    parser.add_argument(
        "--omit-references",
        action="store_true",
        help="exclude the held-out UltraChat reference responses",
    )
    return parser.parse_args()


# Escape characters with special meanings in ordinary LaTeX text.
def escape_latex(text: str) -> str:
    # Ordered character replacements for prose copied from the JSON report.
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(character, character) for character in text)


# Preserve paragraph boundaries while converting model prose to LaTeX.
def format_prose(text: str) -> str:
    # Normalized text without trailing whitespace on individual lines.
    normalized = "\n".join(line.rstrip() for line in text.strip().splitlines())
    # Paragraphs separated by one or more blank lines.
    paragraphs = [part.strip() for part in normalized.split("\n\n") if part.strip()]
    # Escaped paragraphs with single line breaks retained explicitly.
    formatted_paragraphs = [
        escape_latex(paragraph).replace("\n", " " + r"\\" + "\n")
        for paragraph in paragraphs
    ]
    return "\n\n".join(formatted_paragraphs) or r"\emph{No response recorded.}"


# Load the report and verify the structure required by the converter.
def read_report(path: Path) -> list[dict[str, Any]]:
    if not path.is_file():
        raise SystemExit(f"Input report does not exist: {path}")

    try:
        # Parsed JSON content from the completed experiment.
        report = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise SystemExit(f"Invalid JSON in {path}: {error}") from error

    if not isinstance(report, list) or not report:
        raise SystemExit("The input report must be a non-empty JSON list.")

    for index, example in enumerate(report, start=1):
        if not isinstance(example, dict):
            raise SystemExit(f"Example {index} is not a JSON object.")
        # Fields required for each qualitative comparison.
        missing_fields = {
            "prompt",
            "held_out_reference",
            "generations",
        } - set(example)
        if missing_fields:
            raise SystemExit(
                f"Example {index} is missing fields: {', '.join(sorted(missing_fields))}"
            )
        if not isinstance(example["generations"], dict):
            raise SystemExit(f"Example {index} has a non-object generations field.")
    return report


# Return model labels in the preferred order without dropping unexpected labels.
def ordered_model_labels(generations: dict[str, Any]) -> list[str]:
    # Known labels that occur in this example.
    known_labels = [label for label in MODEL_ORDER if label in generations]
    # Any additional labels emitted by a modified experiment.
    extra_labels = sorted(set(generations) - set(MODEL_ORDER))
    return known_labels + extra_labels


# Render the entire qualitative report as a readable LaTeX fragment.
def build_latex(report: list[dict[str, Any]], include_references: bool) -> str:
    # Generated LaTeX source accumulated one line at a time.
    lines = [
        "% Generated by qualitative_generations_to_latex.py; do not edit by hand.",
        r"\section{Qualitative generation comparison}",
        "",
    ]

    for example_index, example in enumerate(report, start=1):
        lines.extend(
            [
                rf"\subsection{{Held-out prompt {example_index}}}",
                r"\paragraph{Prompt}",
                r"\begin{quote}\small",
                format_prose(str(example["prompt"])),
                r"\end{quote}",
                "",
            ]
        )

        if include_references:
            lines.extend(
                [
                    r"\paragraph{Held-out reference}",
                    r"\begin{quote}\small",
                    format_prose(str(example["held_out_reference"])),
                    r"\end{quote}",
                    "",
                ]
            )

        # Model responses associated with the current held-out prompt.
        generations = example["generations"]
        for model_label in ordered_model_labels(generations):
            lines.extend(
                [
                    rf"\paragraph{{{escape_latex(model_label)}}}",
                    r"\begin{quote}\small",
                    format_prose(str(generations[model_label])),
                    r"\end{quote}",
                    "",
                ]
            )

        if example_index != len(report):
            lines.extend([r"\clearpage", ""])

    return "\n".join(lines)


# Convert the selected JSON report and save its LaTeX representation.
def main() -> None:
    # User-selected converter settings.
    args = parse_args()
    # Validated qualitative examples from the experiment.
    report = read_report(args.input)
    # Rendered LaTeX fragment containing all comparisons.
    latex_source = build_latex(report, not args.omit_references)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(latex_source, encoding="utf-8")
    print(f"Wrote {len(report)} qualitative comparisons to: {args.output}")


if __name__ == "__main__":
    main()
